modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="infinitedimensions"
version="1.0.0"
displayName="Infinite Dimensions"
description='''
Dimensões e crafts infinitos gerados proceduralmente.
Jogue um Orbe de Combinação no portal do Nether para acessar
dimensões únicas baseadas na combinação de itens e nomes.
'''

[[dependencies.infinitedimensions]]
    modId="forge"
    mandatory=true
    versionRange="[47.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.infinitedimensions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
